"""
generate_calibration_table.py

Turns a full-range calibration sweep (captured with rollmap_logger.py while
slowly driving the bed from one end of its travel to the other) into a
compact, downsampled lookup table saved as an Arduino header file.

Why this exists:
    The relationship between encoder rotations and actual bed angle is
    nonlinear (typical of actuator + pivot-arm mechanisms), so a single
    "degrees per rotation" constant only works near wherever it was
    calibrated. This script builds a table of real (rotations, roll)
    points across the WHOLE range, so the firmware can interpolate
    between nearby points instead of assuming one constant ratio.

How to collect the input data:
    1. Run rollmap_logger.py while slowly, smoothly driving the bed
       through its full range of motion ONE DIRECTION ONLY (e.g. fully
       flat -> fully reclined). Don't reverse direction mid-sweep -
       the table assumes rotations and roll both move monotonically.
    2. Rename the resulting CSV (e.g. "rollmap_live.csv") to
       "calibration_sweep.csv", or just change INPUT_CSV below.
    3. Run this script:  python generate_calibration_table.py
    4. Copy the generated calibration_table.h into your Arduino sketch
       folder (same folder as the .ino file), replacing the old stub.

Usage:
    python generate_calibration_table.py
"""

import csv

# ---- Settings you may need to change ----
INPUT_CSV = "calibration_sweep.csv"   # output from rollmap_logger.py, renamed
OUTPUT_HEADER = "calibration_table.h"
MAX_TABLE_POINTS = 300                  # keep the table small enough for ESP8266 RAM/flash
# -------------------------------------------


def load_points(path):
    points = []
    with open(path, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rot = int(row["abs_rotations"])
            roll = float(row["roll"])
            points.append((rot, roll))
    return points


def dedupe_and_sort(points):
    # Multiple samples can share the same rotation count (e.g. while
    # paused) - average their roll and keep one entry per rotation count.
    by_rot = {}
    for rot, roll in points:
        by_rot.setdefault(rot, []).append(roll)
    merged = [(rot, sum(rolls) / len(rolls)) for rot, rolls in by_rot.items()]
    merged.sort(key=lambda p: p[0])
    return merged


def downsample(points, max_points):
    if len(points) <= max_points:
        return points
    step = len(points) / max_points
    result = []
    i = 0.0
    while int(i) < len(points):
        result.append(points[int(i)])
        i += step
    if result[-1] != points[-1]:
        result.append(points[-1])
    return result


def main():
    points = load_points(INPUT_CSV)
    if len(points) < 2:
        print(f"Not enough data in {INPUT_CSV} - need at least 2 points.")
        return

    points = dedupe_and_sort(points)
    points = downsample(points, MAX_TABLE_POINTS)

    with open(OUTPUT_HEADER, "w") as f:
        f.write("#pragma once\n\n")
        f.write("// Auto-generated by generate_calibration_table.py\n")
        f.write("// Nonlinear rotations <-> roll calibration table.\n\n")
        f.write(f"#define CAL_TABLE_SIZE {len(points)}\n\n")

        f.write("const int32_t calRotations[CAL_TABLE_SIZE] PROGMEM = {\n  ")
        f.write(", ".join(str(p[0]) for p in points))
        f.write("\n};\n\n")

        f.write("const float calRoll[CAL_TABLE_SIZE] PROGMEM = {\n  ")
        f.write(", ".join(f"{p[1]:.2f}" for p in points))
        f.write("\n};\n")

    print(f"Wrote {len(points)} calibration points to {OUTPUT_HEADER}")
    print(f"Rotation range: {points[0][0]} to {points[-1][0]}")
    print(f"Roll range: {points[0][1]:.2f} to {points[-1][1]:.2f}")


if __name__ == "__main__":
    main()
